env:
  global:
    - CC_TEST_REPORTER_ID=680d1574e6b0f3467f84dfc0edf87a8fb561f96c0c1610d81b81d00ee719a549

language: node_js

node_js:
  - '11'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn test